# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
#      - run:
#          name: Install CocoaPods
#          command: pod install
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: PetAdoption
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
  bump-build:
    macos:
      xcode: "11.2.1"
    environment:
      - LC_ALL: "en_US.UTF-8"
      - LANG: "en_US.UTF-8"
    steps:
      - checkout
      - run:
          name: Installing gem dependencies
          command: bundle install
      - add_ssh_keys:
          fingerprints:
            - "c7:0f:24:08:5d:46:30:ec:d9:2c:05:86:78:51:02:02"
      - run:
          name: Bump the build number and commit
          command: bundle exec fastlane bump
  deploy-beta:
    macos:
      xcode: "11.2.1"
    environment:
      - LC_ALL: "en_US.UTF-8"
      - LANG: "en_US.UTF-8"
    steps:
      - checkout
      - run:
          name: Installing gem dependencies
          command: bundle install
      - add_ssh_keys:
          fingerprints:
            - "03:ba:57:70:9c:79:66:eb:c5:34:fd:79:77:03:38:da"
      - run:
          name: Deploy new build to TestFlight
          command: bundle exec fastlane submit_to_testflight
          
workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - bump-build:
          requires:
            - build-and-test
          filters:
            branches:
              only: staging
            tags:
              only: /.*/
      - deploy-beta:
          requires:
            - build-and-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^builds.*/
