# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.2.1"
    steps:
      - checkout
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: PetAdoption
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
          
workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
